
server:
  port: 6060

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    #driver-class-name:org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
