server:
  port: 6060

# JSP 경로 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    # url: jdbc:h2:C:\Users\dita810\programming\db\temp;
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    # driver-class-name: org.h2.Driver
    username:
    password:
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql
      encoding: UTF-8
      mode: always
mybatis:
  mapper-locations:
    - classpath:Mapper/*_mapper.xml
  configuration:
    map-underscore-to-camel-case: true
